### ISSUE TITLE
Add useMemo and useCallback to the toggler menu items

### ISSUE THREAD

**Issue by blopa** [blopa/Resume-Builder#20]
The components on `src/components/ResumeDrawerItems` need a bit of refactoring, just by adding `useMemo` and `useCallback` to key points would improve a lot of the performance.

Happy hacking.

**Comment by milenagd** [comment]
Hey, can I take this one?

**Comment by blopa** [comment]
Of course :)

**Comment by milenagd** [comment]
Hey @blopa  I just opened the PR.
I am looking forward to seeing your review :)

**Comment by milenagd** [comment]
And can you assign this issue for me, please?

**Comment by blopa** [comment]
That's awesome, thank you so much for your contribution! 🤝

**Comment by milenagd** [comment]
Thank you!!
