### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by vanhoutenbos** [blopa/Resume-Builder#72]
Hi,

Is it possible to add to the description that it must be a .JSON file? I uploaded a .txt file with a valid JSON and it failed :(

Orginal text: I'm not sure if this should still be working uploading any files even the example doesn't work

**Comment by Borgaard** [comment]
It's working, though I'm not sure how. Good luck with your resume.

**Comment by blopa** [comment]
Hey @vanhoutenbos, the JSON schema is a bit of a mess, to be honest, so depending on how you generate your own JSON file it might not work if you don't use the correct schema.

But the example file should work, I just tried with [this file](https://raw.githubusercontent.com/blopa/Resume-Builder/863e9e7/resume.json) and it works fine.

Maybe you can try the [build](https://resume-builder.js.org/en/build) feature and create one from scratch?

Cheers

**Comment by vanhoutenbos** [comment]
Hey!

It does seem to work as long as the extension is actually a .json file!
How come the JSON is a mess? The JSON resume v1.0.0 looks like a good format to use just some small thing missing from LinkedIn like city and projects/featured with in an employee
